name: Python formatter and linter

on: [push]

jobs:
  python-linting-formatting:
    runs-on: ubuntu-latest # Run the runner on a ubuntu image
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3 # Checkout the repo to the runner
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install and run formatter and linter
      run: |
        export PYTHONPATH=$GITHUB_PATH
        python -m venv venv
        source ./venv/bin/activate
        pip install --upgrade pip
        pip install blue
        pip install pylint
        blue --diff --exclude '' build/
        pylint build/camera --exit-zero
        pylint build/db-handler/app --exit-zero
        pylint build/figurines --exit-zero
        pylint build/vision --exit-zero
